name: easy_ads_flutter
description: Easy Ads is a wrapper around famous ad packages which let you integrate ads easily
version: 2.8.1
homepage: https://github.com/nooralibutt/easy-ads
repository: https://github.com/nooralibutt/easy-ads

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  collection: ^1.19.1
  unity_ads_plugin: ^0.3.25
  applovin_max: ^4.5.0
  easy_audience_network: ^0.0.7
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true